name: Code Quality & Accessibility

on: [push, workflow_dispatch]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Initialize package.json
      run: |
        if [ ! -f package.json ]; then
          echo '{"name":"ci-project","version":"1.0.0", "scripts": {}, "dependencies": {}}' > package.json
        fi

    - name: Generate Lockfile
      run: npm install --package-lock-only

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'

    - name: Install Tools
      run: |
        npm install eslint stylelint axe-core pa11y playwright @axe-core/playwright --no-package-lock --no-save

    - name: Run ESLint (JavaScript)
      run: |
        eslint '**/*.js' \
          --format '{{file}}:{{line}}:{{column}} - {{message}} [{{ruleId}}]' \
          > eslint-report.txt || true

    - name: Run Stylelint (CSS)
      run: |
        stylelint '**/*.css' \
          --custom-formatter ./node_modules/stylelint-formatter-markdown \
          > stylelint-report.md || true

    - name: Run HTML Validator
      run: |
        find . -name '*.html' -exec html-validate {} \; \
          --formatter html \
          > html-validate-report.html || true

    - name: Run Accessibility Tests
      run: |
        npx playwright test accessibility.spec.js --reporter=line,json || true
      working-directory: ./tests

    - name: Generate Consolidated Report
      run: |
        echo "# Code Quality Report" > full-report.md
        echo "## JavaScript Issues" >> full-report.md
        [ -s eslint-report.txt ] && cat eslint-report.txt >> full-report.md || echo "No issues" >> full-report.md
        
        echo "\n## CSS Issues" >> full-report.md
        [ -s stylelint-report.md ] && cat stylelint-report.md >> full-report.md || echo "No issues" >> full-report.md
        
        echo "\n## Accessibility Issues" >> full-report.md
        [ -f tests/playwright-report.json ] && \
          jq -r '.tests[0].results[] | "File: \(.title)\nLine: \(.lineNumber)\nError: \(.error.message)\n"' \
          tests/playwright-report.json >> full-report.md || \
          echo "No accessibility issues found" >> full-report.md

        echo "\n# Recommendations" >> full-report.md
        cat <<EOT >> full-report.md
        ### JavaScript
        - Use modern ES6 syntax
        - Add error handling
        
        ### CSS
        - Use CSS variables
        - Validate responsive layouts
        
        ### Accessibility
        - Semantic HTML elements
        - ARIA landmarks
        EOT

    - name: Upload Report
      uses: actions/upload-artifact@v4
      with:
        name: code-quality-report
        path: |
          full-report.md
          html-validate-report.html
